# Generated by Django 3.2.12 on 2023-09-16 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.TextField()),
                ('date', models.DateField()),
                ('vaccancy', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='COMPANY',
        ),
        migrations.AddField(
            model_name='guidelines',
            name='COMPANY',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mock.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='LOGIN',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='mock.login'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField()),
                ('details', models.TextField()),
                ('GUIDE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock.guide')),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('op1', models.TextField()),
                ('op2', models.TextField()),
                ('op3', models.TextField()),
                ('op4', models.TextField()),
                ('ans', models.TextField()),
                ('TEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock.test')),
            ],
        ),
    ]
