# Generated by Django 3.2.12 on 2023-09-16 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0002_auto_20230916_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='GUIDE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mock.guide'),
            preserve_default=False,
        ),
    ]
