# Generated by Django 3.2.12 on 2023-09-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0003_test_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubts',
            name='reply',
            field=models.CharField(max_length=200),
        ),
    ]
