# Generated by Django 3.2.12 on 2023-09-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0004_alter_doubts_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='vaccancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=200)),
                ('vacncy', models.CharField(max_length=200)),
                ('qualif', models.CharField(max_length=200)),
                ('exp', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=200)),
                ('det', models.TextField()),
                ('COMPANY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock.company')),
            ],
        ),
    ]
