# Generated by Django 3.2.12 on 2023-09-19 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0005_vaccancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.TextField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock.user')),
                ('VACCANCY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock.vaccancy')),
            ],
        ),
    ]
