# Generated by Django 3.2.12 on 2023-09-21 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0006_app_req'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('res', models.CharField(max_length=200)),
                ('ans', models.CharField(max_length=200)),
                ('QUESTIONS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock.questions')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock.user')),
            ],
        ),
    ]
