# Generated by Django 3.2.12 on 2023-09-21 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0008_uplds'),
    ]

    operations = [
        migrations.CreateModel(
            name='vac_qn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans', models.TextField()),
                ('VACCANCY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock.vaccancy')),
            ],
        ),
    ]
